lib/linter-tslint.coffee

Positioning of warnings is incorrect, and they also all show up as errors, which isn’t appropriate for a linting failure. This commit fixes the range to show linting failures in the right place and also changes the level from error to warning.
Sorry about the bad PR history, I thought I would only have one fix to send up but then there were two and I am exceptionally lazy right now and am doing everything through GitHub instead of cloning locally. So if you merge this you will also get the fix for #7.

Fix incorrect positioning and warning level

---

lib/linter-tslint.coffee

Fixes #7 
I basically just copied what linter-jshint does to find the correct configuration.

Add configuration pathfinding

---

lib/init.coffee

This fixes linter for me on windows, fixes #30 as well.

Normalize the file path so tslint works for windows

---

lib/init.coffee

Currently, `Linter.findConfiguration` is called with `undefined` as
its first parameter.  This bypasses `tslint`'s configuration-finding
logic, as it explicitly checks for a `null` first parameter.  Therefore
one cannot use `tslint`'s option to set a `tslintConfig` attribute in
`package.json`. This PR corrects that behavior.

Update Linter.findConfiguration's first parameter to null

---

lib/init.coffee
package.json

- Try using local tslint package instead of prebuilt.
- Add useLocalTslint option.
- Fix some coffeelint warnings.
- Clear code.

Using local tslint

---

lib/init.coffee
package.json

Use `atom-package-deps` to automatically install `linter` if it isn't already installed.
Fixes #27.

Auto-install linter

---

.travis.yml
README.md
coffeelint.json
lib/init.coffee
package.json

@park9140 I want to setup CI (via https://travis-ci.org/), but admin rights required.
Coffeelint to start. I will add specs in future.

CI, coffeelint and travis

---

CHANGELOG.md
README.md
lib/init.coffee
package.json

Fix #65 I think.
@Arcanemagus @park9140 
This contains one breaking change. ```rulesDirectory``` from Atom package config has to be absolute path. It is much clearer and better than old resolving: 
```
directory = path.join textEditor.project.getPaths()[0], @rulesDirectory
```

Resolve config rules directories

---

lib/init.coffee

It seems that tslint may be giving us absolute paths for custom rules definitions (possibly a change of behavior?). This PR changes the behavior to not double-root paths if they are already absolute.

Fix path resolution for custom rules directories

---

lib/init.coffee

Currently, the linter configuration (tslint.json) is located and parsed using the tslint module packaged with the plugin. This is incorrect when another version of tslint is in use, which happens when useLocalTslint is true, and a suitable tslint version is found.
This is preventing me from using this atom plugin, because I'm using a tslint version that allows comments in the JSON configuration, but the tslint packaged with atom doesn't support that yet. In any case, it seems wrong to parse the configuration with one version of tslint, and then use it with another version.
Please consider merging this, and thank you very much for your work on this plugin!

Parse tslint.json using the configured linter.

---

lib/init.coffee
package.json

Atom packages are running with Content Security Policy (CSP) set to disallow `eval-like` behavior. Recent change in Typescript (https://github.com/Microsoft/TypeScript/pull/9580) added code that uses `new Function(...)` which will cause `linter-tslint` package to fail to initialize with the error as seen in #104.
This PR uses package `loophole` (https://github.com/atom/loophole) created by the Atom team to specifically address issues like this. I've also commented on the above mentioned PR and will try to open an issue with the Typescript team. Meanwhile, this workaround restores functionality of `linter-tslint` when used with `typescript@next`.

Use `loophole` package to to fix #104

---

.travis.yml
package.json
spec/.eslintrc.js
spec/fixtures/invalid/invalid.ts
spec/fixtures/invalid/tsconfig.json
spec/fixtures/invalid/tslint.json
spec/fixtures/valid/tsconfig.json
spec/fixtures/valid/tslint.json
spec/fixtures/valid/valid.ts
spec/linter-tslint-spec.js

Add some specs testing that the linter is working. Also brings in and configures ESLint to lint the specs.
This also fixes the CI testing, as the previous tests weren't testing this package at all, and without specs they couldn't be updated.
Fixes #48.

Add basic specs

---

lib/main.js
package.json

Thanks for `linter-tslint`! It doesn't seem to work with the latest version of `tslint`, so I've updated the source to work with TSLint v4.
It all seems to work fine for me – let me know if there's anything I can help with to get this merged!

Update for TSLint v4

---

lib/main.js
package.json
spec/linter-tslint-spec.js

Update to `eslint-config-airbnb-base@10.0.1` including updates to `eslint@^3.9.1` and `eslint-plugin-import@^2.1.0` to satisfy its peerDependencies. Cleans up the configuration a tiny bit and fixes the new lint issues.
Closes #118.
Closes #119.

Update ESLint configuration

---

.travis.yml

Whitelist the Greenkeeper branches so it can fully test dependency
updates.

Whitelist the Greenkeeper branches

---

lib/main.js
package.json

-  Adding command to fix TS files.
-  Added option to skip .d.ts files.
-  Adding linter name so that it appears in the history log.

Adding command to fix TS files + other changes (see desc.)

---

lib/main.js

It uses the rules severity if there (if the project uses tslint@5), but defaults to warning, like before.

support tslint@5

---

lib/main.js
spec/fixtures/invalid/tslint.json
spec/linter-tslint-spec.js

In addition, the severity returned by this package was "Warning" (upper-case 'W') which according to [this](https://github.com/steelbrain/linter/blob/master/lib/validate/index.js) isn't valid.

Updating UTs to support both TSLint4 and TSLint5 issues

---

lib/main.js

Reduce the activation time by:
* Defering dependency loading till necessary
* Pushing package dependency checking into an idle callback
On my "pristine" profile this brings activation from an average of 350.8 ms down to 6.8 ms.

Reduce activation time

---

lib/main.js
spec/linter-tslint-spec.js

Fixes [#155](https://github.com/AtomLinter/linter-tslint/issues/155)

Checking for null/undefined filePath from editor.

---

lib/main.js
lib/worker.js
lib/workerHelper.js
package.json

Loosely based on @Arcanemagus's work on [eslint/task-api](https://github.com/AtomLinter/linter-eslint/tree/arcanemagus/task-api)
* Specs now run a tad slower since each test needs to instantiate a task proccess

Refactored to perform linting/fixing on async worker task

---

README.md
lib/main.js
lib/worker.js
package.json
spec/fixtures/invalid-typechecked/invalid-typechecked.ts
spec/fixtures/invalid-typechecked/tsconfig.json
spec/fixtures/invalid-typechecked/tslint.json
spec/fixtures/valid-typechecked/tsconfig.json
spec/fixtures/valid-typechecked/tslint.json
spec/fixtures/valid-typechecked/valid-typechecked.ts
spec/linter-tslint-spec.js

Attempting to fix #109 (building on @zaggino’s code snippet in that issue)
This PR enables [semantic rules](https://palantir.github.io/tslint/usage/type-checking/) by passing a program object to the linter to enable type checking. This resolves warnings that appear in the developer tools console (<kbd>Command</kbd><kbd>Option</kbd><kbd>i</kbd>) when certain TSLint rules are used, e.g.:
```
Warning: The 'no-unused-variable' rule requires type checking
```
This code makes `linter-tslint` runs very slowly on my machine. Warnings like this appear:
```
Handling of 'mousewheel' input event was delayed for 16200 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responive.
```
I’m not sure how to resolve this. Any suggestions are welcomed.

Pass a program object to the linter to enable type checking

---

lib/worker.js
package.json
spec/fixtures/no-config/noConfig.ts
spec/linter-tslint-spec.js

Two issues in one:
**Firstly**, there was a regression I caused when copying the `rulesDirectory` code over to worker.js in [#158](https://github.com/AtomLinter/linter-tslint/pull/158). I missed the fact it used to refer to `this.` (which is now `config.`), so a circular reference was caused, which led `tslint` to have kittens, leading to the worker hanging.
**Secondly**, if `tslint` hit an issue, it would cause the worker to hang.

Fixing bug where the worker thread would hang if there wasn't a tslint.json file

---

lib/main.js

Fixes [#161](https://github.com/AtomLinter/linter-tslint/issues/161)

Fixing old reference to this.lint() that was left from refactoring in fix on save

---

lib/worker.js
package.json
spec/linter-tslint-spec.js

Rule details now show like 
> Foo is not allowed! ([foo-rule]())

Adding link to rule documentation

---

lib/worker.js

Currently the worker will hang if an error occurs during the finding of the configuration file. This fixes that by moving the `try{}` higher to encompass it.
Also fixing the error sent from the worker task, this allows the stack to show properly.

Fixing error handling from worker. Also accounting for errors finding config. file

---

lib/main.js
lib/worker.js
package.json

Howdy, all! 👋 
I stumbled across #189 earlier today after wishing for the exact same feature... it's fairly simple and `linter-eslint` already has a similar option, so I decided it was worth wrangling their implementation into `linter-tslint` as well.
There were some minor linting issues with the current codebase due to recent versions of eslint (you can see what I'm talking about in the CI report for #195) so I took the initiative to resolve those as well. Two of them were super minor and well-founded, but the other one introduced by v4.6.0 was a bit silly (as others have [mentioned](https://github.com/eslint/eslint/pull/8102#issuecomment-326848403),) so I went ahead and // eslint-disabled the relevant lines to avoid mucking the style up without a second opinion. Anyway, I hope this is …

Implement feature request #189 (Option to use global tslint instance)

---

lib/worker.js

Fix invocation of Linter.createProgram() to use full tsconfig path

---

lib/worker.js
package-lock.json
package.json
spec/linter-tslint-spec.js

Upgrade to the v2 version of the linter API, allowing this provider to continue working with newer versions of linter.
Fixes #234.

Upgrade to linter v2 API

---

.github_changelog_generator
.travis.yml
package-lock.json
package.json

To ease the modification/contribution to publish pipeline there has been some discussion of adopting a continuous deployment system for AtomLinter packages. To accomplish this we are making use of [`semantic-release`](https://github.com/semantic-release/semantic-release) and [`@semantic-release/apm-config`](https://github.com/semantic-release/apm-config).
This pull request has been [dynamically created using a script](https://gist.github.com/keplersj/8bc7622ea741c0964d12842bfc679c5d). While the result is not perfect, it does accompish most of the grunt work of adopting continous deployment. There is some reconciliation that needs to be done before this can be merged.
Among the things needed to be reconciled, an [APM Token](https://atom.io/account) and [GitHub …

Initial Adoption of Continous Deployment using semantic-release

---

package.json

Somehow the definition of the service as v2 didn't get committed in the original PR.

Declare service as v2

---

lib/main.js

Changing the old `lintOnFly` to `lintsOnChange` was missed as part of #238.
Fixes #247.

lintsOnChange wasn't defined
